services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: rajesh00007/backend:04
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    image: rajesh00007/frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

volumes:
  mongo-data:
