- hosts: app
  become: yes

  vars:
    docker_user: YOUR_DOCKER_USERNAME
    docker_pass: YOUR_DOCKER_TOKEN

  tasks:

    - name: Docker login
      docker_login:
        username: "{{ secrets.DOCKER_USERNAME }}"
        password: "{{ secrets.DOCKER_PASSWORD }}"

    - name: Copy docker compose file
      copy:
        src: ../docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml

    - name: Deploy containers
      command: docker compose up -d
