- hosts: app
  become: yes

  tasks:

    - name: Create app folder
      file:
        path: /home/ubuntu/app
        state: directory

    - name: Copy docker-compose
      copy:
        src: ../docker-compose.yml
        dest: /home/ubuntu/app/docker-compose.yml
        force: yes

    - name: Pull latest images
      command: /usr/local/bin/docker-compose pull
      args:
        chdir: /home/ubuntu/app

    - name: Remove old containers
      command: /usr/local/bin/docker-compose down
      args:
        chdir: /home/ubuntu/app

    - name: Restart containers
      command: /usr/local/bin/docker-compose up -d
      args:
        chdir: /home/ubuntu/app
