name: app pipeline

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      # ---------- Frontend ----------
      - name: cache deps
        id: cache
        uses: actions/cache@v4
        with:
          path: frontend/package-lock.json
          key: node-modules-${{hashFiles('frontend/package-lock.json')}}
      - name: Install frontend deps
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      # ---------- Backend ----------
      - name: cache deps
        id: cache2
        uses: actions/cache@v4
        with:
          path: backend/package-lock.json
          key: node-modules-${{hashFiles('backend/package-lock.json')}}
      - name: Install backend deps
        if: steps.cache2.outputs.cache-hit != 'true'
        working-directory: backend
        run: npm ci

      - name: Show project files
        run: ls -R
