name: app pipeline

on:
  push:
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: |
            frontend/package-lock.json
            backend/package-lock.json

      - run: npm ci
        working-directory: frontend

      - run: npm run lint
        working-directory: frontend

      # Backend lint
      - run: npm ci
        working-directory: backend

      - run: npm run lint
        working-directory: backend

      # Enable Docker buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build frontend image
      - name: Build frontend image
        run: docker build -t rajesh00007/frontend:latest ./frontend

      #trivyscan for frontend
      - name: Run Trivy scan (frontend)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'rajesh00007/frontend:latest'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
      
      #trivy scan for backend    
      # Build backend image
      - name: Build backend image
        run: docker build -t rajesh00007/backend:latest ./backend

      - name: Run Trivy scan (backend)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'rajesh00007/backend:latest'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'

      # Push images
      - name: Push frontend
        run: docker push rajesh00007/frontend:latest

      - name: Push backend
        run: docker push rajesh00007/backend:latest
